// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Test

#ifndef _TEST_UI_H
#define _TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void TaskBarSlide_Animation(lv_obj_t * TargetObject, int delay);
void TaskBarHide_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Taskbar;
void ui_event_WiFI(lv_event_t * e);
extern lv_obj_t * ui_WiFI;
extern lv_obj_t * ui_Label6;
void ui_event_Slider3(lv_event_t * e);
extern lv_obj_t * ui_Slider3;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Checkbox2;
extern lv_obj_t * ui_Keyboard2;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1695069766);    // assets\colourful-spectrum-4k-hd-wallpaper-800x480.png
LV_IMG_DECLARE(ui_img_r_355x162_png);    // assets\R_355x162.png

LV_FONT_DECLARE(ui_font_Font1);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
