// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Test

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H


void addDropdownOptions();
void changebritnes(lv_event_t * e);
void wificonnect(lv_event_t * e);



#endif
