// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Test

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen1, &ui_img_1695069766, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, -39);
    lv_obj_set_y(ui_Slider1, -206);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -212);
    lv_obj_set_y(ui_Label1, -206);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Slider value is:0 point");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Taskbar = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Taskbar, 800);
    lv_obj_set_height(ui_Taskbar, 183);
    lv_obj_set_x(ui_Taskbar, 0);
    lv_obj_set_y(ui_Taskbar, -334);
    lv_obj_set_align(ui_Taskbar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Taskbar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFI = lv_btn_create(ui_Taskbar);
    lv_obj_set_width(ui_WiFI, 100);
    lv_obj_set_height(ui_WiFI, 80);
    lv_obj_set_x(ui_WiFI, -331);
    lv_obj_set_y(ui_WiFI, -33);
    lv_obj_set_align(ui_WiFI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_WiFI);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "WiFi");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider3 = lv_slider_create(ui_Taskbar);
    lv_slider_set_range(ui_Slider3, 25, 255);
    lv_slider_set_mode(ui_Slider3, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_Slider3, 200, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 1, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 162);
    lv_obj_set_height(ui_Slider3, 41);
    lv_obj_set_x(ui_Slider3, -150);
    lv_obj_set_y(ui_Slider3, -50);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Slider3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Slider3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WiFI, ui_event_WiFI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
