// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Test

#ifndef _UI_EVENTS_Main_H
#define _UI_EVENTS_Main_H

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /*extern "C"*/
#endif
extern void button1(lv_event_t *e);
extern void button2(lv_event_t *e);
extern void button3(lv_event_t *e);
extern void button4(lv_event_t *e);
extern void button5(lv_event_t *e);
extern void button6(lv_event_t *e);
extern void button7(lv_event_t *e);
extern void button8(lv_event_t *e);
extern void button9(lv_event_t *e);
extern void button0(lv_event_t *e);
void devide(lv_event_t *e);
void multiplecation(lv_event_t *e);
void subtraction(lv_event_t *e);
void adding(lv_event_t *e);
void removeone(lv_event_t *e);
void calculate(lv_event_t *e);
#endif
