// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Test

#ifndef _TEST_UI_Main_H
#define _TEST_UI_Main_H

#ifdef __cplusplus
extern "C"
{
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers_main.h"
#include "ui_events_main.h"
void ui_Screen1_screen_init_mian(void);
void ui_Screen6_screen_init_mian(void);
void ui_Screen7_screen_init_mian(void);
void ui_Screen_calculator_screen_init_mian(void);

///////////////////// VARIABLES ////////////////////
extern lv_obj_t * ui_Apps;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_back_label;
extern lv_obj_t * ui_hue;
extern lv_obj_t * ui_hue_label;
//////////////////CALCULATOR/////////////////////////
extern lv_obj_t * ui_calculator_button;
extern lv_obj_t * ui_calculator_label;
///////////// CALCULATOR KEY BOARD///////////////////
extern lv_obj_t * ui_calculator_number_1;
extern lv_obj_t * ui_calculator_number_1_lable;
extern lv_obj_t * ui_calculator_number_2;
extern lv_obj_t * ui_calculator_number_2_lable;
extern lv_obj_t * ui_calculator_number_3;
extern lv_obj_t * ui_calculator_number_3_lable;
extern lv_obj_t * ui_calculator_number_4;
extern lv_obj_t * ui_calculator_number_4_lable;
extern lv_obj_t * ui_calculator_number_5;
extern lv_obj_t * ui_calculator_number_5_lable;
extern lv_obj_t * ui_calculator_number_6;
extern lv_obj_t * ui_calculator_number_6_lable;
extern lv_obj_t * ui_calculator_number_7;
extern lv_obj_t * ui_calculator_number_7_lable;
extern lv_obj_t * ui_calculator_number_8;
extern lv_obj_t * ui_calculator_number_8_lable;
extern lv_obj_t * ui_calculator_number_9;
extern lv_obj_t * ui_calculator_number_9_lable;
extern lv_obj_t * ui_calculator_number_0;
extern lv_obj_t * ui_calculator_number_0_lable;
extern lv_obj_t * ui_calculator_panel;
extern lv_obj_t * ui_calculator_number_mulltiply;
extern lv_obj_t * ui_calculator_number_mulltiply_lable;
extern lv_obj_t * ui_calculator_number_devide;
extern lv_obj_t * ui_calculator_number_devide_lable;
extern lv_obj_t * ui_calculator_number_addition;
extern lv_obj_t * ui_calculator_number_addition_lable;
extern lv_obj_t * ui_calculator_number_subtraction;
extern lv_obj_t * ui_calculator_number_subtractio_lable;
extern lv_obj_t * ui_calculator_number_equals;
extern lv_obj_t * ui_calculator_number_equals_lable;
extern lv_obj_t * ui_calculator_number_removeone;
extern lv_obj_t * ui_calculator_number_removeone_lable;
extern lv_obj_t * ui_calculator_textbox;
//////////////////////////////////////////////////
extern lv_obj_t * ui_snake_button;
extern lv_obj_t * ui_snake_label;
extern lv_obj_t * ui_snake_Button3;
extern lv_obj_t * ui_snake_Button2;
extern lv_obj_t * ui_snake_Arrow_UP;
extern lv_obj_t * ui_snake_Arrow_Down;
extern lv_obj_t * ui_snake_Arrow_Left;
extern lv_obj_t * ui_snake_Arrow_Right;
extern lv_obj_t * ui_snake_Arrow_UP_lable;
extern lv_obj_t * ui_snake_Arrow_Down_lable;
extern lv_obj_t * ui_snake_Arrow_Left_lable;
extern lv_obj_t * ui_snake_Arrow_Right_lable;
extern lv_obj_t * ui_snake_box;
extern lv_obj_t * ui_snake_jcon_out;
extern lv_obj_t * ui_snake_jcon_in;
///////////////////// SCREENS ////////////////////
extern lv_obj_t * ui_Screen7;
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Screen_calculator;
extern lv_obj_t *ui_Screen_snake_game;
//////////////////////////////////////////////////
extern void app_select(lv_event_t *e);
extern void mainscreen(lv_event_t *e);
extern void lamp_control(lv_event_t *e);
extern void calcurator(lv_event_t *e);
extern void snakemain(lv_event_t *e);
void ui_init_main(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
